/* C Abstract Syntax Implementation generated by the BNF Converter. */

#include <stdio.h>
#include <stdlib.h>
#include "Absyn.h"


/********************   Prog    ********************/
Program make_Prog(ListFunction p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog!\n");
        exit(1);
    }
    tmp->kind = is_Prog;
    tmp->u.prog_.listfunction_ = p1;
    return tmp;
}/********************   DFunc    ********************/
Function make_DFunc(Type p1, Id p2, ListArg p3, ListStm p4)
{
    Function tmp = (Function) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating DFunc!\n");
        exit(1);
    }
    tmp->kind = is_DFunc;
    tmp->u.dfunc_.type_ = p1;
    tmp->u.dfunc_.id_ = p2;
    tmp->u.dfunc_.listarg_ = p3;
    tmp->u.dfunc_.liststm_ = p4;
    return tmp;
}/********************   ADecl    ********************/
Arg make_ADecl(Type p1, Id p2)
{
    Arg tmp = (Arg) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ADecl!\n");
        exit(1);
    }
    tmp->kind = is_ADecl;
    tmp->u.adecl_.type_ = p1;
    tmp->u.adecl_.id_ = p2;
    return tmp;
}/********************   ListFunction    ********************/
ListFunction make_ListFunction(Function p1, ListFunction p2)
{
    ListFunction tmp = (ListFunction) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListFunction!\n");
        exit(1);
    }
    tmp->function_ = p1;
    tmp->listfunction_ = p2;
    return tmp;
}/********************   ListStm    ********************/
ListStm make_ListStm(Stm p1, ListStm p2)
{
    ListStm tmp = (ListStm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListStm!\n");
        exit(1);
    }
    tmp->stm_ = p1;
    tmp->liststm_ = p2;
    return tmp;
}/********************   ListArg    ********************/
ListArg make_ListArg(Arg p1, ListArg p2)
{
    ListArg tmp = (ListArg) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListArg!\n");
        exit(1);
    }
    tmp->arg_ = p1;
    tmp->listarg_ = p2;
    return tmp;
}/********************   SExp    ********************/
Stm make_SExp(Exp p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SExp!\n");
        exit(1);
    }
    tmp->kind = is_SExp;
    tmp->u.sexp_.exp_ = p1;
    return tmp;
}
/********************   SReturn    ********************/
Stm make_SReturn(Exp p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SReturn!\n");
        exit(1);
    }
    tmp->kind = is_SReturn;
    tmp->u.sreturn_.exp_ = p1;
    return tmp;
}/********************   EInt    ********************/
Exp make_EInt(Integer p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EInt!\n");
        exit(1);
    }
    tmp->kind = is_EInt;
    tmp->u.eint_.integer_ = p1;
    return tmp;
}
/********************   EStr    ********************/
Exp make_EStr(Id p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EStr!\n");
        exit(1);
    }
    tmp->kind = is_EStr;
    tmp->u.estr_.id_ = p1;
    return tmp;
}
/********************   ELs    ********************/
Exp make_ELs(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ELs!\n");
        exit(1);
    }
    tmp->kind = is_ELs;
    tmp->u.els_.exp_1 = p1;
    tmp->u.els_.exp_2 = p2;
    return tmp;
}/********************   Tint    ********************/
Type make_Tint()
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Tint!\n");
        exit(1);
    }
    tmp->kind = is_Tint;
    return tmp;
}/********************   Iden    ********************/
QualId make_Iden(Ident p1)
{
    QualId tmp = (QualId) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Iden!\n");
        exit(1);
    }
    tmp->kind = is_Iden;
    tmp->u.iden_.ident_ = p1;
    return tmp;
}
/********************   Idens    ********************/
QualId make_Idens(QualId p1, Ident p2)
{
    QualId tmp = (QualId) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Idens!\n");
        exit(1);
    }
    tmp->kind = is_Idens;
    tmp->u.idens_.qualid_ = p1;
    tmp->u.idens_.ident_ = p2;
    return tmp;
}
