package cpp_grammar.Absyn; // Java Package generated by the BNF Converter.

public class EStr  extends Exp {
  public final String string_;
  public EStr(String p1) { string_ = p1; }

  public <R,A> R accept(cpp_grammar.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp_grammar.Absyn.EStr) {
      cpp_grammar.Absyn.EStr x = (cpp_grammar.Absyn.EStr)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
