package cpp_grammar.Absyn; // Java Package generated by the BNF Converter.

public class Fun  extends Function {
  public final Type type_;
  public final String ident_;
  public final ListArg listarg_;
  public final ListStm liststm_;
  public Fun(Type p1, String p2, ListArg p3, ListStm p4) { type_ = p1; ident_ = p2; listarg_ = p3; liststm_ = p4; }

  public <R,A> R accept(cpp_grammar.Absyn.Function.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp_grammar.Absyn.Fun) {
      cpp_grammar.Absyn.Fun x = (cpp_grammar.Absyn.Fun)o;
      return this.type_.equals(x.type_) && this.ident_.equals(x.ident_) && this.listarg_.equals(x.listarg_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.type_.hashCode())+this.ident_.hashCode())+this.listarg_.hashCode())+this.liststm_.hashCode();
  }


}
