package cpp_grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class Function implements java.io.Serializable {
  public abstract <R,A> R accept(Function.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cpp_grammar.Absyn.Fun p, A arg);

  }

}
