package cpp_grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class QualId implements java.io.Serializable {
  public abstract <R,A> R accept(QualId.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cpp_grammar.Absyn.Iden p, A arg);

  }

}
