package cpp_grammar.Absyn; // Java Package generated by the BNF Converter.

public class SDecl  extends Stm {
  public final Arg arg_;
  public SDecl(Arg p1) { arg_ = p1; }

  public <R,A> R accept(cpp_grammar.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp_grammar.Absyn.SDecl) {
      cpp_grammar.Absyn.SDecl x = (cpp_grammar.Absyn.SDecl)o;
      return this.arg_.equals(x.arg_);
    }
    return false;
  }

  public int hashCode() {
    return this.arg_.hashCode();
  }


}
